<a href="https://colab.research.google.com/github/DanielFlorez999/Estructura-de-datos-II/blob/Listas/Listas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
NewList = ["el hacking","las motos","el futbol","los carros","la F1"]
print(NewList);
print(NewList[0]);
print(NewList[1]);
print(NewList[2]);
print(NewList[3]);
print(NewList[4]);

['el hacking', 'las motos', 'el futbol', 'los carros', 'la F1']
el hacking
las motos
el futbol
los carros
la F1


In [ ]:
OtraList = NewList
print(OtraList);
for item in OtraList:
    print(item);
print(OtraList[0]);
print(OtraList[1]);
print(OtraList[2]);
print(OtraList[3]);
print(OtraList[4]);

['el hacking', 'las motos', 'el futbol', 'los carros', 'la F1']
el hacking
las motos
el futbol
los carros
la F1
el hacking
las motos
el futbol
los carros
la F1


In [ ]:
FruitsList = ['manzana','pera','piña','uva','naranja','mandarina','sandia']
print(FruitsList[3])

FruitsList = ['manzana','pera','piña','uva','naranja','mandarina','sandia']
print(FruitsList[-3])

uva
naranja


In [ ]:
EdadList = [30,22,23,15,65,8]

for edad in EdadList:
  print(EdadList)

for i in range (len(EdadList)):
  print(EdadList[i])

indice = 0

while indice < len(EdadList):
  print(EdadList[indice])
  indice += 1

[30, 22, 23, 15, 65, 8]
[30, 22, 23, 15, 65, 8]
[30, 22, 23, 15, 65, 8]
[30, 22, 23, 15, 65, 8]
[30, 22, 23, 15, 65, 8]
[30, 22, 23, 15, 65, 8]
30
22
23
15
65
8
30
22
23
15
65
8


In [ ]:
EdadList = [30,22,23,15,65,8]

indice = 0

while indice < len(EdadList):
  print(EdadList[indice])
  indice += 1

30
22
23
15
65
8


In [ ]:
EdadList = [30,22,23,15,65,8]

EdadList.append(18)
EdadList.append(10)
EdadList.append(25)

print(EdadList)

[30, 22, 23, 15, 65, 8, 18, 10, 25]


In [ ]:
EdadList = [30,22,23,15,65,8]

EdadList = EdadList + [19,11,26]

print(EdadList)

[30, 22, 23, 15, 65, 8, 19, 11, 26]


In [ ]:
Numeros = [2, 4, 8, 6, 0]

Numeros = Numeros + [3, 5, 9, 7, 1]

print(Numeros);



[2, 4, 8, 6, 0, 3, 5, 9, 7, 1]


In [ ]:
Marcas = ["Apple", "Lg", "Hp", "Samsung", "Xiaomi"]

Marcas.pop(2)
Marcas.pop(-1)

print(Marcas)

['Apple', 'Lg', 'Samsung']


In [ ]:
Marcas = ["Apple", "Lg", "Hp", "Hp", "Samsung", "Xiaomi"]

Marcas.remove("Hp")
Marcas.remove("Xiaomi")


print(Marcas)

['Apple', 'Lg', 'Hp', 'Samsung']


In [ ]:
Nombres = ["Daniel", "Juan", "Ana", "Maria", "Pedro"]
Identificacion = [1000362256, 39741256, 987654321, 123456789, 951475396]

if(Nombres = "Daniel")
  print(Identificacion)


In [ ]:
Nombres =[]
Identificaciones = []
Direcciones = []

Tamaño = 3

for i in range(Tamaño):
  print('Ingrese los datos de la persona:', i + 1)
  Nombre = input('Nombre: ')
  Identificacion = input('Identificacion: ')
  Direccion = input('Direccion: ')

  Nombres.append(Nombre)
  Identificaciones.append(Identificacion)
  Direcciones.append(Direccion)


for i in range(Tamaño):
  print('Mostrando los nombres de la persona:', i + 1)
  print('Nombre: '+ Nombres[i])
  print('Identificacion: ' + Identificaciones[i])
  print('Direccion: ' + Direcciones[i])

Ingrese los datos de la persona: 1
Nombre: A
Identificacion: 123
Direccion: Calle 1
Ingrese los datos de la persona: 2
Nombre: b
Identificacion: 321
Direccion: Calle 2
Ingrese los datos de la persona: 3
Nombre: C
Identificacion: 564
Direccion: Calle 3
Mostrando los nombres de la persona: 1
Nombre: A
Identificacion: 123
Direccion: Calle 1
Mostrando los nombres de la persona: 2
Nombre: b
Identificacion: 321
Direccion: Calle 2
Mostrando los nombres de la persona: 3
Nombre: C
Identificacion: 564
Direccion: Calle 3


In [ ]:
import numpy as np

lista = [1, 2, 3, 4, 5]

vector = np.array(lista)

vector = np.array(lista)

print('Vector created from a List: ')
print(vector)

Vector created from a List: 
[1 2 3 4 5]


In [ ]:
import numpy as np

Lista = [1],[2],[3],[4],[5]

vector = np.array(Lista)
vector = np.array(lista)

print('Vector created from a List: ')
print(vector)


Vector created from a List: 
[1 2 3 4 5]


In [ ]:
import numpy as np

lista = [10, 20, 30, 40, 50]
Lista2 = [1, 2, 3, 4, 5]

vector = np.array(lista)
vector2 = np.array(Lista2)

print('Vector created from a List: ')
print(vector)

print('Vector created from a List 2: ')
print(vector2)

vector_add = vector + vector2
print('Vector Addition: ')
print(vector_add)




Vector created from a List: 
[10 20 30 40 50]
Vector created from a List 2: 
[1 2 3 4 5]
Vector Addition: 
[11 22 33 44 55]


In [ ]:
import numpy as np

lista = [10, 20, 30, 40, 50]
Lista2 = [1, 2, 3, 4, 5, 6, 7]

vector = np.array(lista)
vector2 = np.array(Lista2)

print('Vector created from a List: ')
print(vector)

print('Vector created from a List 2: ')
print(vector2)

vector_add = vector + vector2
print('Vector Addition: ')
print(vector_add)


Vector created from a List: 
[10 20 30 40 50]
Vector created from a List 2: 
[1 2 3 4 5 6 7]


ValueError: operands could not be broadcast together with shapes (5,) (7,) 

In [ ]:
import numpy as np

lista = [10, 20, 30, 40, 50]
Lista2 = [1, 2, 3, 4, 5]

vector = np.array(lista)
vector2 = np.array(Lista2)

print('Vector created from a List: ')
print(vector)

print('Vector created from a List 2: ')
print(vector2)

vector_add = vector - vector2
print('Vector Sustraction: ')
print(vector_add)

Vector created from a List: 
[10 20 30 40 50]
Vector created from a List 2: 
[1 2 3 4 5]
Vector Sustraction: 
[ 9 18 27 36 45]


In [ ]:
import numpy as np

lista = [10, 20, 30, 40, 50]
Lista2 = [1, 2, 3, 4, 5]

vector = np.array(lista)
vector2 = np.array(Lista2)

print('Vector created from a List: ')
print(vector)

print('Vector created from a List 2: ')
print(vector2)

vector_add = vector * vector2
print('Vector Multiplicacion: ')
print(vector_add)

Vector created from a List: 
[10 20 30 40 50]
Vector created from a List 2: 
[1 2 3 4 5]
Vector Multiplicacion: 
[ 10  40  90 160 250]


In [ ]:
import numpy as np

lista = [10, 20, 30, 40, 50]
Lista2 = [1, 2, 3, 4, 5]

vector = np.array(lista)
vector2 = np.array(Lista2)

print('Vector created from a List: ')
print(vector)

print('Vector created from a List 2: ')
print(vector2)

vector_add = vector / vector2
print('Vector Dvision: ')
print(vector_add)

Vector created from a List: 
[10 20 30 40 50]
Vector created from a List 2: 
[1 2 3 4 5]
Vector Dvision: 
[10. 10. 10. 10. 10.]


In [ ]:
import numpy as np

lista1 = [10, 20, 30, 40, 50]
lista2 = [1, 1, 1, 1, 1]

vector1 = np.array(lista1)
vector2 = np.array(lista2)

print('Vector created from a List: ')
print(vector1)

print('Vector created from a List 2: ')
print(vector2)

vector_final = vector.dot(vector2)
print('Vector Final: ')
print(vector_final)

Vector created from a List: 
[10 20 30 40 50]
Vector created from a List 2: 
[1 1 1 1 1]
Vector Final: 
150


In [ ]:
import numpy as np

lista1 = [10, 20, 30, 40, 50]
lista2 = [1, 1, 1, 1, 1]

vector1 = np.array(lista1)
vector2 = np.array(lista2)

print('Vector created from a List: ')
print(vector1)

print('Vector created from a List 2: ')
print(vector2)

vector_final = vector2.dot(vector)
print('Vector Final: ')
print(vector_final)

Vector created from a List: 
[10 20 30 40 50]
Vector created from a List 2: 
[1 1 1 1 1]
Vector Final: 
150


In [ ]:
#Ejemplo set con Type

s = set([5, 4, 6, 8, 8, 1])
print(s)
print(type(s))

{1, 4, 5, 6, 8}
<class 'set'>


In [ ]:
#Ejemplo set con las llaves

s = {5, 4, 6, 8, 8, 1}
print(s)
print(type(s))

{1, 4, 5, 6, 8}
<class 'set'>


In [ ]:
#Intento de unir lista con set

lista = ["Peru","Argentina"]
#s = set(["Mexico", "España", lista])
lista.append("Mexico")
lista.append("España")
print(lista)
#print(s)


['Peru', 'Argentina', 'Mexico', 'España']


In [ ]:
#Metodo for para imprimir la funcion set en vertical

s = set([5, 6, 7, 8])
for ss in s:
  print(ss)

8
5
6
7


In [ ]:
#Metodo LEN

s = set([1, 2, 3, 4, 6, 5])
print (len(s))

6


In [ ]:
#Metodo LEN

s = {3, 1, 8, 8, 8, 8, 6, 7, 7, 4}
print(len(s))
print(s)

6
{1, 3, 4, 6, 7, 8}


In [ ]:
#Metodo TRUE o FALSE

s = {"Guitarra", "Piano", "Violin", "Guitarra"}
print("Piano" in s)

ss = {"carro", "avion", "moto",}
print("bus" in ss)

True
False


In [ ]:
#Metodo UNION

s1 = {1, 2, 3}
s2 = {3, 4, 5}

print(s1 | s2)

{1, 2, 3, 4, 5}


In [ ]:
#Metodo ADD

s = {1, 2}
s.add(3)
print(s)

{1, 2, 3}


In [ ]:
#Metodo REMOVE

s = {1, 2}
s.remove(2)
print(s)


{1}


In [ ]:
#Metodo REMOVE error

s = {1, 2}
s.remove(3)
print(s)

KeyError: 3

In [ ]:
#Metodo DISCARD

s = {1, 2}
s.discard(3)
print(s)

{1, 2}


In [ ]:
#Metodo POP

s = {1, 2}
s.pop()
print(s)

{2}


In [ ]:
#Metodo CLEAR

s = {1, 2}
s.clear()
print(s)

set()


In [ ]:
#Metodo UNION

s1 = {1, 2, 3}
s2 = {3, 4, 5}

print(s1.union(s2))

{1, 2, 3, 4, 5}


In [ ]:
#Metodo INTERSECTION

s1 = {1, 2, 3}
s2 = {3, 4, 5}

print(s1.intersection(s2))

In [ ]:
#Ejercicio Practico Actividad sesion 6

FrontendTeam = {"HTML","CSS","JavaScript","React"}
BackendTeam = {"Python","SQL","JavaScript","Django"}

FrontendTeam.add("Vue.js")
BackendTeam.remove("Django")

print( FrontendTeam | BackendTeam)
print( FrontendTeam & BackendTeam)
print( FrontendTeam - BackendTeam)
print( FrontendTeam ^ BackendTeam)

{'CSS', 'Python', 'HTML', 'React', 'SQL', 'Vue.js', 'JavaScript'}
{'JavaScript'}
{'CSS', 'HTML', 'React', 'Vue.js'}
{'Python', 'HTML', 'CSS', 'React', 'SQL', 'Vue.js'}


In [3]:
#Taller sesion 7
#Ejercicio 8 Analisis de encuesta

respuestas = [5, 4, 3, 5, 5, 2, 4, 5, 1, 5]

ContadorMax = 0;

for i in respuestas:
  if i == 5:
    ContadorMax += 1

opciones = set(respuestas)

print("Opciones únicas de respuesta:", opciones)
print("Total de personas muy satisfechas (5):", ContadorMax)

Opciones únicas de respuesta: {1, 2, 3, 4, 5}
Total de personas muy satisfechas (5): 5


In [5]:
#Taller sesion 7
#Ejercicio 10 Filtrado de correo electronico

spam_emails = {"spam1@example.com", "ofertas@mal.com", "dudoso@mail.net"}

correo_entrante = "usuario.normal@email.com"

print("Correo entrante:", correo_entrante)
if correo_entrante in spam_emails:
    print("Alerta de SPAM")
else:
    print("Correo seguro")

correo_entrante = "ofertas@mal.com"

print("Segundo Correo entrante:", correo_entrante)
if correo_entrante in spam_emails:
    print("Alerta de SPAM")
else:
    print("Correo seguro")

log_verificaciones = ["usuario.normal@email.com", "ofertas@mal.com"]

print("Log de verificaciones:", log_verificaciones)


Correo entrante: usuario.normal@email.com
Correo seguro
Segundo Correo entrante: ofertas@mal.com
Alerta de SPAM
Log de verificaciones: ['usuario.normal@email.com', 'ofertas@mal.com']


In [6]:
#Taller sesion 7
#Ejercicio 3 Gestión de Tareas Pendientes

tareas = ["Enviar reporte", "Revisar correos"] #primeros datos
print("LISTA DE TAREAS")
print(tareas)
nueva_tarea = "Llamar al cliente" #añadimos una nueva tarea
tareas.append(nueva_tarea)
print("\nTareas actualizadas")
print(tareas) #se imprime la lista con la nueva tarea
tareas[0] = tareas[0] + " ..Completada.. " #marcamos la primera tarea como completada

print("\nLista final")
print(tareas) #se imprime la lista final

LISTA DE TAREAS
['Enviar reporte', 'Revisar correos']

Tareas actualizadas
['Enviar reporte', 'Revisar correos', 'Llamar al cliente']

Lista final
['Enviar reporte ..Completada.. ', 'Revisar correos', 'Llamar al cliente']


In [ ]:
#Taller sesion 7
#Ejercicio 4 Control de Asistencia a un Evento

asistentes_ingresados = {"ID_1122", "ID_3344"} #dejamos el conjunto con los asistentes iniciales
persona_llegando = "ID_5566" #creamos la variable con la persona que llega
if persona_llegando in asistentes_ingresados: #verificamos si ya esta en el conjunto
    print("Ya habias ingresado") #si ya esta mostramos este mensajito
else:
    asistentes_ingresados.add(persona_llegando) #si no esta lo agregamos al conjunto
    print("Bienvenido") #mostramos este mensaje
persona_llegando = "ID_1122" #simulamos que llega la persona ID_1122
if persona_llegando in asistentes_ingresados: #verificamos si ya esta en el conjunto
    print("Ya habias ingresado") #si ya esta mostramos este mensaje
else:
    asistentes_ingresados.add(persona_llegando) #si no esta lo agregamos al conjunto
    print("Bienvenido") #mostramos este mensaje
print("\nConjunto final de asistentes:") #imprimimos el conjunto final
print(asistentes_ingresados)

In [ ]:
#Taller sesion 7
#Ejercicio 1 Registro de Nuevos Usuarios en una App
# Crea una lista de usuarios registrados
Usuarios_Registrados=["ana_dev","luis_ux","carlos_pm"]
# Convierte la lista a un conjunto para obtener usuarios únicos
Usuarios_Unicos= set (Usuarios_Registrados)
# Define un nuevo usuario
nuevo_usuario= "luis_ux"
# Comprueba si el nuevo usuario ya está en el conjunto de usuarios únicos
if nuevo_usuario in Usuarios_Unicos:
    # Si el usuario existe, imprime un mensaje
    print("El usuario ya existe")
else:
    # Si el usuario no existe, agrégalo al conjunto
    Usuarios_Unicos.add(nuevo_usuario)
    # Imprime el conjunto actualizado de usuarios únicos (el orden puede variar en un conjunto)
    print(Usuarios_Unicos)
    # Imprime un mensaje de éxito
    print("El usuario se ha registrado correctamente")
# Define otro nuevo usuario
nuevo_usuario2= "sofia_qa"
# Comprueba si el segundo nuevo usuario ya está en el conjunto de usuarios únicos
if nuevo_usuario2 in Usuarios_Unicos:
  # Si el usuario existe, imprime un mensaje
  print("El usuario ya existe")
else:
 # Si el usuario no existe, agrégalo al conjunto
 Usuarios_Unicos.add(nuevo_usuario2)
 # Imprime el conjunto actualizado de usuarios únicos, unidos por comas
 print(",".join(Usuarios_Unicos))
 # Imprime un mensaje de éxito
 print("El usuario se ha registrado correctamente")
# Imprime una línea en blanco para espaciar
print()
# Imprime la lista original de usuarios registrados, unidos por guiones
print("-".join(Usuarios_Registrados))

In [ ]:
#Taller sesion 7
#Ejercicio 9 Gestión de Ingredientes para una Receta
# Define una lista de ingredientes para la masa
ingredientes_masa = ["harina", "mantequilla", "agua", "sal"]
# Define una lista de ingredientes para el relleno
ingredientes_relleno = ["queso", "espinaca", "huevo", "sal"]
# Combina las dos listas de ingredientes
Ingredientes_juntos= ingredientes_masa + ingredientes_relleno
# Imprime la lista combinada de ingredientes, unidos por guiones
print("-".join(Ingredientes_juntos))
# Imprime una línea en blanco para espaciar
print()
# Convierte la lista combinada a un conjunto para obtener ingredientes únicos para una lista de compras
lista_compras_final= set(Ingredientes_juntos)
# Imprime el conjunto de ingredientes únicos, unidos por guiones (el orden puede variar en un conjunto)
print("-".join(lista_compras_final))